### PR TITLE
It's necessary to add Cordova platforms before run.

### PR DESCRIPTION
**Pull request by matyaspeto**
I tried to fix the run script to make it work under Windows as well, without any success :(

### CODE REVIEW

**Comment by kartsims** [comment]
Could you please try the `windows` branch I just created ?

It triggers a `cordova prepare`  on NPM's `postinstall` hook. It should be tested in a new folder (do not just switch branch, but rather clone again the repo)

**Comment by matyaspeto** [comment]
Great, now the platforms are added correctly.

Unfortunately, on Windows the "npm run browser" still failing, because of the "PORT=3000" statement.
As I see, Windows uses the "set" command to set env variables, so the npm script should be:

`"browser": "cordova prepare browser && set PORT=3000 && node build/dev-server.js",`

But this will not set the port correctly on OSX, so I'm puzzled.

**Comment by kartsims** [comment]
Yeah, I didn't think about that.

Sorry that is fixed on the `windows` branch. If it's OK for you, I'll merge to `master`

**Comment by matyaspeto** [comment]
Sure, go ahead :)

**Pull request closed without merging**
